### PR TITLE
Added arp-scan to Dockerfile

### PR DESCRIPTION
**Pull request by cyberjunky**
Another attempt. Sorry for the mess ;P
Where can I find instructions to build/test it locally?

### CODE REVIEW

**Comment by pvizeli** [comment]
This is not available for https://pkgs.alpinelinux.org/packages?name=arp-scan&branch=v3.9

Maybe you can compile it in?

**Comment by cyberjunky** [comment]
Ah. It is available in testing, but last build is from last year?
https://pkgs.alpinelinux.org/packages?name=arp-scan&branch=edge&repo=testing

Have to see how to submit this, I guess I have to follow this guide.
https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package

Wil try soon.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-homeassistant/blob/master/base/Dockerfile#L24-L34

**Comment by cyberjunky** [comment]
Yes clear, got the commands listed, will test and commit later:
```
RUN apk add --no-cache --virtual .build-dependencies autoconf automake \
        libpcap-dev \
    && git clone --depth 1 -b 1.9.5 https://github.com/royhills/arp-scan \
    && cd arp-scan \
    && autoreconf --install \
    && ./configure \
    && make -j$(nproc) \
    && make install \
    && apk del .build-dependencies \
    && cd /usr/src \
    && rm -rf /usr/src/arp-scan
```

**Comment by cyberjunky** [comment]
I tested building the docker image with:
```
docker build --build-arg BUILD_FROM=alpine:3.9 --build-arg BUILD_ARG=amd64 .
```
But some packages didn't build (missing pip3 error)
I fixed them in my Dockerfile by adding ' python3-dev' to the pkg add commands.
But I left them out of my commit, since I cannot imagine the bugs were there, and issues must be caused by my wrong building command, or something else.

**Pull request merged**
