### PR TITLE
Adds pianobar

### PR DESCRIPTION
**Pull request by ludeeus**
Required by <https://www.home-assistant.io/integrations/pandora>

Package info:
https://pkgs.alpinelinux.org/package/v3.9/community/x86_64/pianobar

### CODE REVIEW

**Comment by pvizeli** [comment]
Do you have test this?

I think the 100kb are fine.

**Comment by ludeeus** [comment]
I have not tested it, there was a user on discord that was having issues, and I figured this would be the best solution to it.

Alternatives would be for the user to exec into it and installing (after each update) or rolling a custom image.

**Comment by pvizeli** [comment]
I'm open for a good dynamic packages install, maybe also with manifest.

That is from community repository. I'm not sure if you can install this kind of packages out of the box.

**Comment by ludeeus** [comment]
A dynamic handler for this would be preferable, currently all our images are based on alpine so for those it should be quite doable.
But if the manifest is used for this I guess Home Assistant would be responsible for installing missing packages, what about non-docker installations, they would just be skipped?

There are 2 other (non-popular) alternatives to this:
- Add detailed instructions on how to roll your own images.
- Remove integrations that rely on system packages that are not in the images.

***

> That is from community repository. I'm not sure if you can install this kind of packages out of the box.

Looks like it's working (from my hassio installation):
```bash
docker exec  homeassistant apk add pianobar
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/2) Installing libao (1.2.2-r0)
(2/2) Installing pianobar (2018.06.22-r1)
Executing busybox-1.30.1-r2.trigger
OK: 186 MiB in 154 packages
```

**Comment by pvizeli** [comment]
I would suggest making an `hassio_apk` on the manifest. Then we make something similar to wheels. We can also forward this manifest data to the supervisor if they are present and the supervisor deals with packages.

**Pull request merged**
